name: Build

on:
  push

jobs:
  create-release:
    name: Build and Create Tagged release
    runs-on: ubuntu-latest

    steps:
      - name: Install archive tools
        run: sudo apt install zip

      - name: Checkout source code
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          ref: ${{ github.event.repository.default_branch }}


      - name: Install dependencies
        run: cd web && yarn

      - name: Run build
        run: cd web && yarn run build

      - name: Update tag ref
        uses: EndBug/latest-tag@latest
        with:
          tag-name: ${{ github.ref_name }}

      - name: Bundle files
        run: |
          mkdir -p ./temp/vHud
          mkdir -p ./temp/vHud/web/
          mkdir -p ./temp/vHud/lib/
          cp ./{LICENSE,README.md,fxmanifest.lua,ui.lua} ./temp/vHud
          cp ./lib/MySQL.lua ./temp/vHud/lib
          cp -r ./dist ./temp/vHud
          cp -r ./web/build ./temp/vHud/web/
          cd ./temp && zip -r ../vHud.zip ./vHud

      - name: Create Release
        uses: 'marvinpinto/action-automatic-releases@v1.2.1'
        id: auto_release
        with:
          repo_token: '${{ secrets.GITHUB_TOKEN }}'
          title: 'Testing.'
          prerelease: false
          files: vHud.zip

        env:
          CI: false
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}